<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [
            // ── Gratis ──────────────────────────────────────────────────────
            [
                'name'            => 'Blossom Garden',
                'slug'            => 'blossom-garden',
                'description'     => 'Tema floral romantis dengan palet warna pastel lembut.',
                'category'        => 'Floral',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#e8a5b4',
                'color_secondary' => '#f9e4ea',
                'tags'            => json_encode(['floral', 'romantis', 'pastel']),
                'is_active'       => true,
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 342,
            ],
            [
                'name'            => 'Rustic Charm',
                'slug'            => 'rustic-charm',
                'description'     => 'Nuansa rustic yang hangat dan natural.',
                'category'        => 'Rustic',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#8b6f47',
                'color_secondary' => '#f2ebe0',
                'tags'            => json_encode(['rustic', 'natural', 'vintage']),
                'is_active'       => true,
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 189,
            ],
            [
                'name'            => 'Starry Night',
                'slug'            => 'starry-night',
                'description'     => 'Minimalis dengan sentuhan bintang dan langit malam.',
                'category'        => 'Minimalis',
                'event_type'      => 'Ulang Tahun',
                'color_primary'   => '#3b4c8a',
                'color_secondary' => '#eef0fb',
                'tags'            => json_encode(['minimalis', 'bintang', 'biru']),
                'is_active'       => true,
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 156,
            ],
            [
                'name'            => 'Forest Whisper',
                'slug'            => 'forest-whisper',
                'description'     => 'Kesegaran alam dengan dominasi warna hijau.',
                'category'        => 'Alam',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#3d6b4f',
                'color_secondary' => '#edf4f0',
                'tags'            => json_encode(['alam', 'hijau', 'segar']),
                'is_active'       => true,
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 128,
            ],
            [
                'name'            => 'Pastel Breeze',
                'slug'            => 'pastel-breeze',
                'description'     => 'Perpaduan warna pastel ceria dan lembut.',
                'category'        => 'Floral',
                'event_type'      => 'Ulang Tahun',
                'color_primary'   => '#aecfd6',
                'color_secondary' => '#f4fafb',
                'tags'            => json_encode(['pastel', 'ceria', 'soft']),
                'is_active'       => true,
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 97,
            ],
            [
                'name'            => 'Sandy Shore',
                'slug'            => 'sandy-shore',
                'description'     => 'Nuansa pantai dengan gradasi pasir dan laut.',
                'category'        => 'Alam',
                'event_type'      => 'Pertunangan',
                'color_primary'   => '#c8a96e',
                'color_secondary' => '#fdf6ec',
                'tags'            => json_encode(['pantai', 'hangat', 'natural']),
                'is_active'       => true,
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 84,
            ],

            // ── Premium ──────────────────────────────────────────────────────
            [
                'name'            => 'Royal Elegance',
                'slug'            => 'royal-elegance',
                'description'     => 'Desain mewah bernuansa emas untuk pernikahan istimewa.',
                'category'        => 'Mewah',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#c9a84c',
                'color_secondary' => '#f5f0e8',
                'tags'            => json_encode(['mewah', 'gold', 'elegan']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 75000,
                'usage_count'     => 218,
            ],
            [
                'name'            => 'Sakura Bliss',
                'slug'            => 'sakura-bliss',
                'description'     => 'Keindahan bunga sakura yang romantis dan lembut.',
                'category'        => 'Floral',
                'event_type'      => 'Pertunangan',
                'color_primary'   => '#f4a7b9',
                'color_secondary' => '#fef6f8',
                'tags'            => json_encode(['sakura', 'romantis', 'merah muda']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 99000,
                'usage_count'     => 203,
            ],
            [
                'name'            => 'Lavender Dreams',
                'slug'            => 'lavender-dreams',
                'description'     => 'Ketenangan lavender dengan sentuhan modern.',
                'category'        => 'Floral',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#8b7bc8',
                'color_secondary' => '#f0eefb',
                'tags'            => json_encode(['lavender', 'ungu', 'elegan']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 89000,
                'usage_count'     => 175,
            ],
            [
                'name'            => 'Modern Slate',
                'slug'            => 'modern-slate',
                'description'     => 'Desain modern minimalis dengan palet abu elegan.',
                'category'        => 'Modern',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#475569',
                'color_secondary' => '#f1f5f9',
                'tags'            => json_encode(['modern', 'minimalis', 'abu']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 79000,
                'usage_count'     => 142,
            ],
            [
                'name'            => 'Sunrise Coral',
                'slug'            => 'sunrise-coral',
                'description'     => 'Kehangatan fajar dengan warna koral yang cerah.',
                'category'        => 'Modern',
                'event_type'      => 'Ulang Tahun',
                'color_primary'   => '#e8735a',
                'color_secondary' => '#fef3f0',
                'tags'            => json_encode(['koral', 'cerah', 'hangat']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 85000,
                'usage_count'     => 119,
            ],
            [
                'name'            => 'Aqua Marine',
                'slug'            => 'aqua-marine',
                'description'     => 'Kesegaran laut dengan warna biru toska jernih.',
                'category'        => 'Modern',
                'event_type'      => 'Aqiqah',
                'color_primary'   => '#2a9d8f',
                'color_secondary' => '#e8f8f6',
                'tags'            => json_encode(['toska', 'laut', 'segar']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 75000,
                'usage_count'     => 88,
            ],

            // ── Eksklusif ────────────────────────────────────────────────────
            [
                'name'            => 'Midnight Dream',
                'slug'            => 'midnight-dream',
                'description'     => 'Kemewahan gelap dengan aksen emas eksklusif.',
                'category'        => 'Modern',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#1a1a2e',
                'color_secondary' => '#c8a45d',
                'tags'            => json_encode(['modern', 'dark', 'eksklusif']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => true,
                'price'           => 150000,
                'usage_count'     => 97,
            ],
            [
                'name'            => 'Crimson Velvet',
                'slug'            => 'crimson-velvet',
                'description'     => 'Kemewahan merah velvet untuk acara paling berkesan.',
                'category'        => 'Mewah',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#8b1a1a',
                'color_secondary' => '#fdf0f0',
                'tags'            => json_encode(['merah', 'mewah', 'velvet']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => true,
                'price'           => 175000,
                'usage_count'     => 64,
            ],
            [
                'name'            => 'Ivory Lace',
                'slug'            => 'ivory-lace',
                'description'     => 'Keanggunan renda ivory yang timeless dan mewah.',
                'category'        => 'Mewah',
                'event_type'      => 'Pernikahan',
                'color_primary'   => '#b8956a',
                'color_secondary' => '#fdfaf5',
                'tags'            => json_encode(['ivory', 'renda', 'klasik']),
                'is_active'       => true,
                'is_premium'      => true,
                'is_exclusive'    => true,
                'price'           => 199000,
                'usage_count'     => 52,
            ],
        ];

        foreach ($themes as $theme) {
            DB::table('themes')->updateOrInsert(
                ['slug' => $theme['slug']],
                array_merge($theme, [
                    'preview_image_url'  => null,
                    'thumbnail_url'      => null,
                    'created_by_user_id' => null,
                    'created_at'         => now(),
                    'updated_at'         => now(),
                ])
            );
        }
    }
}
