<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = array_merge(
            $this->weddingThemes(),
            $this->birthdayThemes(),
            $this->khitananThemes(),
            $this->aqiqahThemes(),
            $this->genderRevealThemes(),
            $this->syukuranThemes(),
        );

        foreach ($themes as $theme) {
            DB::table('themes')->updateOrInsert(
                ['slug' => $theme['slug']],
                array_merge($theme, [
                    'tags'               => json_encode($theme['tags']),
                    'preview_image_url'  => $theme['preview_image_url'] ?? null,
                    'thumbnail_url'      => $theme['thumbnail_url'] ?? null,
                    'is_active'          => true,
                    'created_by_user_id' => null,
                    'created_at'         => now(),
                    'updated_at'         => now(),
                ])
            );
        }
    }

    private function weddingThemes(): array
    {
        return [
            [
                'name'            => 'Blossom Garden',
                'slug'            => 'blossom-garden',
                'description'     => 'Tema floral romantis dengan palet warna pastel lembut.',
                'category'        => 'Floral',
                'event_type'      => 'wedding',
                'color_primary'   => '#e8a5b4',
                'color_secondary' => '#f9e4ea',
                'tags'            => ['floral', 'romantis', 'pastel'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 342,
            ],
            [
                'name'            => 'Rustic Charm',
                'slug'            => 'rustic-charm',
                'description'     => 'Nuansa rustic yang hangat dan natural.',
                'category'        => 'Rustic',
                'event_type'      => 'wedding',
                'color_primary'   => '#8b6f47',
                'color_secondary' => '#f2ebe0',
                'tags'            => ['rustic', 'natural', 'vintage'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 189,
            ],
            [
                'name'            => 'Emerald & Gold',
                'slug'            => 'them1',
                'description'     => 'Nuansa hijau hutan dan emas yang elegan dengan sentuhan botani.',
                'category'        => 'Klasik',
                'event_type'      => 'wedding',
                'color_primary'   => '#2d5016',
                'color_secondary' => '#c9a84c',
                'tags'            => ['hijau', 'emas', 'elegan'],
                'thumbnail_url'   => '/preview/themes/wedding/them1/assets/img/photos/hero-couple.jpg',
                'preview_image_url' => '/preview/themes/wedding/them1/assets/img/photos/hero-couple.jpg',
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Golden Ivory',
                'slug'            => 'wedding_theme_02',
                'description'     => 'Nuansa gold dan ivory yang mewah dengan sentuhan floral elegan.',
                'category'        => 'Klasik',
                'event_type'      => 'wedding',
                'color_primary'   => '#b8975a',
                'color_secondary' => '#fdf8f2',
                'tags'            => ['gold', 'ivory', 'elegan'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Romantic Blush',
                'slug'            => 'wedding_theme_03',
                'description'     => 'Nuansa blush rose dan emas dengan gaya script romantis.',
                'category'        => 'Romantis',
                'event_type'      => 'wedding',
                'color_primary'   => '#c47c6b',
                'color_secondary' => '#faf6f0',
                'tags'            => ['blush', 'rose', 'romantis'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
            [
                'name'              => 'Royal Maroon',
                'slug'              => 'wedding_theme_06',
                'description'       => 'Tema pernikahan klasik dengan palet cream, gold, dan maroon yang mewah.',
                'category'          => 'Klasik',
                'event_type'        => 'wedding',
                'color_primary'     => '#7a0c2e',
                'color_secondary'   => '#f4efea',
                'tags'              => ['maroon', 'gold', 'klasik'],
                'thumbnail_url'     => '/preview/themes/wedding/wedding_theme_06/assets/photos/hero-couple.jpg',
                'preview_image_url' => '/preview/themes/wedding/wedding_theme_06/assets/photos/hero-couple.jpg',
                'is_premium'        => false,
                'is_exclusive'      => false,
                'price'             => 0,
                'usage_count'       => 0,
            ],
        ];
    }

    private function birthdayThemes(): array
    {
        return [
            [
                'name'            => 'Starry Night',
                'slug'            => 'starry-night',
                'description'     => 'Minimalis dengan sentuhan bintang dan langit malam.',
                'category'        => 'Minimalis',
                'event_type'      => 'birthday',
                'color_primary'   => '#3b4c8a',
                'color_secondary' => '#eef0fb',
                'tags'            => ['minimalis', 'bintang', 'biru'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 156,
            ],
            [
                'name'            => 'Birthday Party',
                'slug'            => 'birthday_theme_01',
                'description'     => 'Pesta ulang tahun ceria penuh balon, confetti, dan kue untuk si kecil.',
                'category'        => 'Ceria',
                'event_type'      => 'birthday',
                'color_primary'   => '#ff5d8f',
                'color_secondary' => '#ffe27a',
                'tags'            => ['pesta', 'balon', 'confetti'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Magical Birthday',
                'slug'            => 'birthday_theme_02',
                'description'     => 'Dunia fantasi istana, pelangi, dan unicorn yang penuh keajaiban.',
                'category'        => 'Fantasi',
                'event_type'      => 'birthday',
                'color_primary'   => '#8b5cf6',
                'color_secondary' => '#fbbf24',
                'tags'            => ['istana', 'pelangi', 'unicorn'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Pesta Hutan Beruang',
                'slug'            => 'birthday_theme_03',
                'description'     => 'Pesta ulang tahun bertema hutan dengan beruang kecil, madu, dan lebah yang lucu.',
                'category'        => 'Ceria',
                'event_type'      => 'birthday',
                'color_primary'   => '#123a2f',
                'color_secondary' => '#ffc24a',
                'tags'            => ['hutan', 'beruang', 'madu'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Pesta Kucing Manis',
                'slug'            => 'birthday_theme_04',
                'description'     => 'Pesta ulang tahun tema kucing manis dengan nuansa pastel pink, ungu, dan mint.',
                'category'        => 'Ceria',
                'event_type'      => 'birthday',
                'color_primary'   => '#F2557E',
                'color_secondary' => '#FFB7D5',
                'tags'            => ['kucing', 'pastel', 'manis'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Kue Bertingkat',
                'slug'            => 'birthday_theme_05',
                'description'     => 'Pesta ulang tahun malam bernuansa ungu gelap dengan animasi kue tiga tingkat yang tersusun sampai lilinnya menyala.',
                'category'        => 'Elegan',
                'event_type'      => 'birthday',
                'color_primary'   => '#241540',
                'color_secondary' => '#FFC847',
                'tags'            => ['kue', 'malam', 'elegan'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Balapan Gokart',
                'slug'            => 'birthday_theme_06',
                'description'     => 'Pesta ulang tahun tema balapan gokart dengan animasi lampu start menyala dan mobil balap melaju masuk lintasan.',
                'category'        => 'Ceria',
                'event_type'      => 'birthday',
                'color_primary'   => '#E63946',
                'color_secondary' => '#FFD23F',
                'tags'            => ['balapan', 'gokart', 'mobil'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Pahlawan Mendarat',
                'slug'            => 'birthday_theme_07',
                'description'     => 'Pesta ulang tahun bergaya komik superhero dengan animasi pahlawan mendarat, ledakan debu, dan gelembung suara.',
                'category'        => 'Ceria',
                'event_type'      => 'birthday',
                'color_primary'   => '#3B2AA8',
                'color_secondary' => '#F0399B',
                'tags'            => ['superhero', 'komik', 'pahlawan'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Ekspedisi Safari',
                'slug'            => 'birthday_theme_08',
                'description'     => 'Pesta ulang tahun tema safari dengan animasi jip melaju dan jerapah, zebra, singa, gajah, serta monyet bermunculan dari balik rumput.',
                'category'        => 'Ceria',
                'event_type'      => 'birthday',
                'color_primary'   => '#B4703C',
                'color_secondary' => '#F5B942',
                'tags'            => ['safari', 'hewan', 'jip'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Studio Kartun',
                'slug'            => 'birthday_theme_09',
                'description'     => 'Pesta ulang tahun tema televisi retro dengan animasi TV menyala dan berganti saluran menampilkan kucing pahlawan, robot, alien, dan bintang ulang tahun.',
                'category'        => 'Ceria',
                'event_type'      => 'birthday',
                'color_primary'   => '#5D4CA8',
                'color_secondary' => '#F7C543',
                'tags'            => ['superhero', 'kartun', 'televisi'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 0,
            ],
        ];
    }

    private function khitananThemes(): array
    {
        return [
            [
                'name'            => 'Sky Blue Junior',
                'slug'            => 'sky-blue-junior',
                'description'     => 'Tema biru langit segar yang cocok untuk khitanan anak.',
                'category'        => 'Minimalis',
                'event_type'      => 'khitanan',
                'color_primary'   => '#4fc3f7',
                'color_secondary' => '#e1f5fe',
                'tags'            => ['biru', 'segar', 'anak'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 174,
            ],
            [
                'name'            => 'Little Hero',
                'slug'            => 'khitanan_theme_01',
                'description'     => 'Tema superhero yang seru dan energik untuk sang jagoan cilik.',
                'category'        => 'Ceria',
                'event_type'      => 'khitanan',
                'color_primary'   => '#e63946',
                'color_secondary' => '#1d3557',
                'tags'            => ['superhero', 'jagoan', 'energik'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Little Prince',
                'slug'            => 'khitanan_theme_02',
                'description'     => 'Nuansa kerajaan yang elegan dan playful untuk pangeran kecil.',
                'category'        => 'Mewah',
                'event_type'      => 'khitanan',
                'color_primary'   => '#3a0ca3',
                'color_secondary' => '#ffd166',
                'tags'            => ['kerajaan', 'pangeran', 'elegan'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 65000,
                'usage_count'     => 0,
            ],
        ];
    }

    private function aqiqahThemes(): array
    {
        return [
            [
                'name'            => 'Baby Bloom',
                'slug'            => 'baby-bloom',
                'description'     => 'Manis dan lembut untuk menyambut buah hati.',
                'category'        => 'Floral',
                'event_type'      => 'aqiqah',
                'color_primary'   => '#f8bbd0',
                'color_secondary' => '#fce4ec',
                'tags'            => ['bayi', 'lembut', 'floral'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 198,
            ],
            [
                'name'            => 'Little Star',
                'slug'            => 'little-star',
                'description'     => 'Bintang kecil yang bersinar untuk sang buah hati.',
                'category'        => 'Minimalis',
                'event_type'      => 'aqiqah',
                'color_primary'   => '#ffe082',
                'color_secondary' => '#fffde7',
                'tags'            => ['bintang', 'kuning', 'lembut'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 154,
            ],
            [
                'name'            => 'Aqua Marine',
                'slug'            => 'aqua-marine',
                'description'     => 'Kesegaran laut dengan warna biru toska jernih.',
                'category'        => 'Modern',
                'event_type'      => 'aqiqah',
                'color_primary'   => '#2a9d8f',
                'color_secondary' => '#e8f8f6',
                'tags'            => ['toska', 'laut', 'segar'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 75000,
                'usage_count'     => 88,
            ],
            [
                'name'            => 'Bismillah Blossom',
                'slug'            => 'bismillah-blossom',
                'description'     => 'Ornamen islami dengan bunga lembut yang penuh berkah.',
                'category'        => 'Islami',
                'event_type'      => 'aqiqah',
                'color_primary'   => '#80cbc4',
                'color_secondary' => '#e0f2f1',
                'tags'            => ['islami', 'floral', 'berkah'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 69000,
                'usage_count'     => 112,
            ],
            [
                'name'            => 'Angel Cloud',
                'slug'            => 'angel-cloud',
                'description'     => 'Desain premium eksklusif dengan nuansa awan putih yang suci.',
                'category'        => 'Mewah',
                'event_type'      => 'aqiqah',
                'color_primary'   => '#b3c7e6',
                'color_secondary' => '#eaf0fb',
                'tags'            => ['awan', 'putih', 'suci'],
                'is_premium'      => true,
                'is_exclusive'    => true,
                'price'           => 135000,
                'usage_count'     => 28,
            ],
            [
                'name'            => 'Little Safari',
                'slug'            => 'aqiqah_theme_01',
                'description'     => 'Petualangan safari yang playful dengan hewan-hewan lucu.',
                'category'        => 'Modern',
                'event_type'      => 'aqiqah',
                'color_primary'   => '#e9a13b',
                'color_secondary' => '#588157',
                'tags'            => ['safari', 'hewan', 'petualangan'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Cute Baby',
                'slug'            => 'aqiqah_theme_02',
                'description'     => 'Bayi lucu di antara awan dan bintang dengan nuansa pastel lembut.',
                'category'        => 'Minimalis',
                'event_type'      => 'aqiqah',
                'color_primary'   => '#a5b4fc',
                'color_secondary' => '#fef9ff',
                'tags'            => ['bayi', 'awan', 'pastel'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
        ];
    }

    private function genderRevealThemes(): array
    {
        return [
            [
                'name'            => 'Pink or Blue',
                'slug'            => 'pink-or-blue',
                'description'     => 'Klasik pink dan biru untuk reveal jenis kelamin si kecil.',
                'category'        => 'Ceria',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#f48fb1',
                'color_secondary' => '#90caf9',
                'tags'            => ['pink', 'biru', 'reveal'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 267,
            ],
            [
                'name'            => 'Balloon Fiesta',
                'slug'            => 'balloon-fiesta',
                'description'     => 'Semarak balon warna-warni untuk momen pengungkapan.',
                'category'        => 'Ceria',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#ce93d8',
                'color_secondary' => '#f3e5f5',
                'tags'            => ['balon', 'pesta', 'ceria'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 183,
            ],
            [
                'name'            => 'Confetti Surprise',
                'slug'            => 'confetti-surprise',
                'description'     => 'Kejutan konfeti yang meriah dan penuh warna.',
                'category'        => 'Ceria',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#7c4dff',
                'color_secondary' => '#ede7f6',
                'tags'            => ['konfeti', 'kejutan', 'ungu'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 59000,
                'usage_count'     => 142,
            ],
            [
                'name'            => 'Sweet Reveal',
                'slug'            => 'sweet-reveal',
                'description'     => 'Manis dan elegan untuk mengumumkan jenis kelamin bayi.',
                'category'        => 'Floral',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#f06292',
                'color_secondary' => '#fce4ec',
                'tags'            => ['manis', 'elegan', 'floral'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 79000,
                'usage_count'     => 94,
            ],
            [
                'name'            => 'Galaxy Reveal',
                'slug'            => 'galaxy-reveal',
                'description'     => 'Desain eksklusif bertema galaksi yang memukau.',
                'category'        => 'Modern',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#311b92',
                'color_secondary' => '#ead1f7',
                'tags'            => ['galaksi', 'bintang', 'eksklusif'],
                'is_premium'      => true,
                'is_exclusive'    => true,
                'price'           => 145000,
                'usage_count'     => 37,
            ],
            [
                'name'            => 'Pink vs Blue',
                'slug'            => 'gender_reveal_theme_01',
                'description'     => 'Duel warna pink dan biru yang seru untuk momen penantian jenis kelamin.',
                'category'        => 'Ceria',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#f472b6',
                'color_secondary' => '#60a5fa',
                'tags'            => ['pink', 'biru', 'reveal'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Little Adventure',
                'slug'            => 'gender_reveal_theme_02',
                'description'     => 'Petualangan balon udara dan pegunungan untuk momen "Boy or Girl?".',
                'category'        => 'Modern',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#fb923c',
                'color_secondary' => '#2dd4bf',
                'tags'            => ['petualangan', 'balon udara', 'pegunungan'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 55000,
                'usage_count'     => 0,
            ],
            [
                'name'            => 'Starlit Night',
                'slug'            => 'gender_reveal_theme_03',
                'description'     => 'Langit malam bertabur bintang dan rembulan untuk menantikan bintang kecil kami.',
                'category'        => 'Elegan',
                'event_type'      => 'gender_reveal',
                'color_primary'   => '#b9a0e8',
                'color_secondary' => '#f3c66d',
                'tags'            => ['bintang', 'bulan', 'dreamy'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 55000,
                'usage_count'     => 0,
            ],
        ];
    }

    private function syukuranThemes(): array
    {
        return [
            [
                'name'            => 'Warm Gathering',
                'slug'            => 'warm-gathering',
                'description'     => 'Kehangatan kebersamaan dengan warna tanah yang nyaman.',
                'category'        => 'Rustic',
                'event_type'      => 'syukuran',
                'color_primary'   => '#d4845a',
                'color_secondary' => '#fdf0e8',
                'tags'            => ['hangat', 'kebersamaan', 'natural'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 221,
            ],
            [
                'name'            => 'Sandy Shore',
                'slug'            => 'sandy-shore',
                'description'     => 'Nuansa pantai dengan gradasi pasir dan laut.',
                'category'        => 'Alam',
                'event_type'      => 'syukuran',
                'color_primary'   => '#c8a96e',
                'color_secondary' => '#fdf6ec',
                'tags'            => ['pantai', 'hangat', 'natural'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 84,
            ],
            [
                'name'            => 'Alhamdulillah',
                'slug'            => 'alhamdulillah',
                'description'     => 'Nuansa islami syukuran dengan ornamen kaligrafi yang indah.',
                'category'        => 'Islami',
                'event_type'      => 'syukuran',
                'color_primary'   => '#388e3c',
                'color_secondary' => '#e8f5e9',
                'tags'            => ['islami', 'kaligrafi', 'hijau'],
                'is_premium'      => false,
                'is_exclusive'    => false,
                'price'           => 0,
                'usage_count'     => 309,
            ],
            [
                'name'            => 'Golden Blessing',
                'slug'            => 'golden-blessing',
                'description'     => 'Syukuran istimewa dengan sentuhan emas yang berkelas.',
                'category'        => 'Mewah',
                'event_type'      => 'syukuran',
                'color_primary'   => '#f9a825',
                'color_secondary' => '#fff8e1',
                'tags'            => ['emas', 'berkah', 'mewah'],
                'is_premium'      => true,
                'is_exclusive'    => false,
                'price'           => 69000,
                'usage_count'     => 156,
            ],
            [
                'name'            => 'Barakah Garden',
                'slug'            => 'barakah-garden',
                'description'     => 'Taman penuh berkah dengan ornamen bunga islami eksklusif.',
                'category'        => 'Islami',
                'event_type'      => 'syukuran',
                'color_primary'   => '#1b5e20',
                'color_secondary' => '#dcedc8',
                'tags'            => ['islami', 'taman', 'berkah'],
                'is_premium'      => true,
                'is_exclusive'    => true,
                'price'           => 125000,
                'usage_count'     => 44,
            ],
        ];
    }
}
